import { useRef } from 'react';
import Head from "next/head";
import Header from "@/components/Header";
import About from "@/components/About";
import Services from '@/components/Services';
import Gallery from '@/components/Gallery';
import Testimonial from '@/components/Testimonial';
import Faq from '@/components/Faq';
import Footer from '@/components/Footer';

export default function Index() {
  const aboutRef = useRef(null);

  const scrollToAbout = () => {
    aboutRef.current.scrollIntoView({ behavior: 'smooth' });
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated byt create next app" ></meta>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
      </Head>
      <Header scrollToAbout={scrollToAbout} />
      <About ref={aboutRef} />
      <Services />
      <Gallery />
      <Testimonial />
      <div className='w-[1200px] h-[2px] bg-[#CCCCCC] flex justify-center ml-48 ' ></div>
      <Faq />
      <Footer scrollToAbout={scrollToAbout} />
    </div>
  );
} 
